[build]
  publish = "Builds/"

[[headers]]
  for = "/Build/*.br"
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "application/octet-stream"

[[headers]]
  for = "/Build/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/Build/*.data"
  [headers.values]
    Content-Type = "application/octet-stream"

[[headers]]
  for = "/Build/*.wasm"
  [headers.values]
    Content-Type = "application/wasm"

[[headers]]
  for = "/Build/*.wasm.br"
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "application/wasm" 

[[headers]]
  for = "/Build/*.symbols.json"
  [headers.values]
    Content-Type = "application/json"

[[headers]]
  for = "/TemplateData/*.json"
  [headers.values]
    Content-Type = "application/json"
